### ISSUE TITLE
Small Business & Schedule 70 research 

### ISSUE THREAD

**Issue by arouault** [18F/statelocal#4]
- Develop talking points for help at the GSA level - good business case to be made 
- Schedule 70 fees
- Quantify Schedule 70 governments  
- Reach out to sb office at GSA to see how we get credit for schedule for sb awards 
26.202-1 Local area set-aside.
The contracting officer may set aside solicitations to allow only local firms within a specific geographic area to compete (see 6.208 ).
(a) The contracting officer, in consultation with the requirements office, shall define the specific geographic area for the local set-aside.
(b) A major disaster or emergency area may span counties in several contiguous States. The set-aside area need not include all the counties in the declared disaster/emergency area(s), but cannot go outside it.
(c) The contracting officer shall also determine whether a local area set-aside should be further restricted to small business concerns in the set-aside area (see part  19).

**Comment by AshleyO85** [comment]
@arouault @pkigongo is this still a need?

**Comment by arouault** [comment]
I think we covered this one a while back! thanks for following up though!
